version: '3.8'

services:
  api:
    image: node:20.11.1
    container_name: api-container
    restart: always
    working_dir: /app
    env_file:
      - .env
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
    ports:
      - 3333:3000
    links:
      - postgres

    depends_on:
      - postgres

    volumes:
      - ./:/app
    command: bash -c "npm i && npm run start:dev" # install node modules and start adonis server

  postgres:
    container_name: postgres-container
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgresdb"
    ports:
      - 5432:5432


volumes:
  postgres: